### ISSUE TITLE
Design the UX/UI!

### ISSUE THREAD

**Issue by Kareemhegazy133** [League-Application/Yuumi.GG-Android-App#5]
Flexible navigation, Easy User Interface and overall the design of the app!

**Comment by gabinho991** [comment]
Done

**Comment by ad828** [comment]
Working to Fix Cardview and work with Material UI Components for a smoother flexible look. Main UI is done for components but needs to be further stylized. This is a rolling issue and will be worked on a bit more throughout all the sprints in addition to the other issues.
